### ISSUE TITLE
No longer does the cleaning

### ISSUE THREAD

**Issue by nicoxxxcox** [isrgrajan/TeamViewer-Cleanup-Tool#2]
Thank you very much for your work! .
But it hasn't been working recently.

**Comment by RatioJuris** [comment]
> Thank you very much for your work! .
> But it hasn't been working recently.

Hi! @nicoxxxcox , thank you for trying. Well, this tool help you to clean the traces from the system, but to make it work again you've to change the Mac address as well and to do so you can Technitium MAC Address Changer.

**Comment by nicoxxxcox** [comment]
Ok, thanks !
I'll test that
